//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W24TP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reponse
    {
        public int RepID { get; set; }
        public string RepText { get; set; }
        public Nullable<int> MsgID { get; set; }
        public string UserID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Message Message { get; set; }
    }
}
